### ISSUE TITLE
it can't use!!!

### ISSUE THREAD

**Issue by cutebear0123** [Code-Oto/PopCat.click_Auto#1]
i go to replit.com and open a repl
i can use ctrl+g to open something
but i put it to console it can't move

https://user-images.githubusercontent.com/72639017/129455628-d93ab07e-5556-4277-a2f4-af69ab96e24c.mp4

**Comment by Code-Oto** [comment]
> i go to replit.com and open a repl
> i can use ctrl+g to open something
> but i put it to console it can't move
> 
> https://user-images.githubusercontent.com/72639017/129455628-d93ab07e-5556-4277-a2f4-af69ab96e24c.mp4
> 
> 

this is for popcat.click

**Comment by cutebear0123** [comment]
> > i go to replit.com and open a repl
> > i can use ctrl+g to open something
> > but i put it to console it can't move
> > 
> >   
> >     
> >     
> > 
> >     screen-capture.mp4
> 
> this is for popcat.click

so what is this
